### ISSUE TITLE
Android keyboard bug

### ISSUE THREAD

**Issue by Fires04** [Fabrik/fabrik#2065] opened 2018-09-12 09:34 UTC
I use Joomla (3.x) with http://fabrikar.com/ - form creator. I created form what works really well but on Android phones I find the big bug. If I touch to input field android keyboard go up and after 1 second it goes down again so it is impossible to write anything to form. Do you have some suggestions?

what I try? 1) update to latest version of plugin 2) try different version of android 3) try on iphone - it works ok

Website: penzion-znojmo.cz Video: https://youtu.be/8jY9xMYaRXE

**Comment by trob** [comment] 2018-09-12 10:04
Can you please post in the forums?
I can't replicate. Fabrik forms on Android are working fine (tested with Chrome, Opera, Samsung "Internet").
Which Joomla template?
Any 3rd party plugins overriding Joomla's JS?

**Comment by Fires04** [comment] 2018-09-12 10:07
Hi ,  I found it is problem with jquery so I disabled jquery and now it
works ok :(

st 12. 9. 2018 v 12:04 odesílatel troester <notifications@github.com>
napsal:

**Comment by Sophist-UK** [comment] 2018-09-12 10:11
1. I have tried your form on both Chrome for Windows and Chrome for Android. I cannot reproduce this bug, but the date picker does not work on Android, the calc of room costs doesn't work on either and submit doesn't work on Android.

2. Please close this issue and move it to the Fabrikar.com forums. Github issues are for confirmed bugs only.

**Closed** 2018-09-12 10:49 UTC
