### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1419] opened 2015-03-23 07:15 UTC
WARNING ::1	deprecated	JDispatcher is deprecated. Use JEventDispatcher instead.
WARNING ::1	deprecated	JSubMenuHelper::getEntries() is deprecated. Use JHtmlSidebar::getEntries() instead.
WARNING ::1	deprecated	JSubMenuHelper::getFilters() is deprecated. Use JHtmlSidebar::getFilters() instead.
WARNING ::1	deprecated	JSubMenuHelper::getAction() is deprecated. Use JHtmlSidebar::getAction() instead.
WARNING ::1	deprecated	This method is typehinted to be an array in \Joomla\Utilities\ArrayHelper::toString.
WARNING ::1	deprecated	renderMessage() is deprecated. Override system message rendering with layouts instead.

**Comment by pollen8** [comment] 2015-04-02 10:43
Hello, where are you seeing the warnings?
If its in the Joomla log then the issue is that whilst these functions are depreciated in the current version of Joomla their new alternatives don't existing in Joomla 2.5 - so as per the road map, i think we can look at this one for 3.4 which drops J2.5 support

**Comment by trob** [comment] 2015-04-02 10:51
it's in logs/fabrik.log.php

**Comment by pollen8** [comment] 2015-04-16 13:54
I'll close this one as its only going to be relevant for 3.5

**Closed by pollen8** 2015-04-16 13:54 UTC
