### ISSUE TITLE
Validation Message is not shown on ajaxified forms

### ISSUE THREAD

**Issue by britzke** [Fabrik/fabrik#1314] opened 2014-09-02 16:30 UTC
When a **list** is set up with ajaxified Links then the validation messages on elements are not shown in the edit form. The validation message for the form is still showing and the form is not closed.
Edit: This is with Joomla! 3.3.3 and Fabrik 3.2 release
Edit 2: If the **list** is de-ajaxified, the validation messages on elements are shown again – as expected.

**Comment by pollen8** [comment] 2015-04-16 16:50
hi this looks like a duplicate of https://github.com/Fabrik/fabrik/issues/1394 which I fixed today

**Closed by pollen8** 2015-04-16 16:50 UTC
