### ISSUE TITLE
list email plugin, WYSIWYG editor enabled, ignores editing

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1780] opened 2016-08-13 16:02 UTC
The first time after loading the list the emails doesn't contain the changes made in the WYSIWYG editor (sending only the text defined in the plugin settings)
It's ok if you are sending again.
It's ok if WYSIWYG is no.
Tested with frontend/Protostar and backend.

**Comment by kstevet** [comment] 2016-09-15 01:22
Seems to be a problem with JCE editor. When I switch the editor in my profile to TinyMCE, the problem is gone... modified text is sent.
A work-around when using JCE is to inserting a "Read More" at end of text.

**Comment by cheesegrits** [comment] 2016-09-19 17:57
Fixed with https://github.com/Fabrik/fabrik/commit/c2a157349ae1cdcc598d54fad9b143279d323333

**Closed by cheesegrits** 2016-09-19 17:57 UTC
